### ISSUE TITLE
how to run this rep to website?

### ISSUE THREAD

**Issue by tiandao-dongguan** [DevExpress/devextreme-documentation#1509]
can anybody tell me how to deploy this rep to website? 
like iis or nginx
thank you

**Comment by Jioh-L-Y-C** [comment]
你可以在本地运行项目吗，用npm

**Comment by Jioh-L-Y-C** [comment]
Can you run the project locally, using NPM

**Comment by AlisherAmonulloev** [comment]
Unfortunately, it is not possible to run this repository as a website because it requires additional utilities that are not published.

I will inform the team about your request. However, it is unlikely that we will publish these utilities in the near future. In the meantime, you can use our online documentation: js.devexpress.com/Documentation.
