### ISSUE TITLE
Running project error

### ISSUE THREAD

**Issue by Jioh-L-Y-C** [DevExpress/devextreme-documentation#1766]
![image](https://user-images.githubusercontent.com/46061532/105787826-330d5680-5fba-11eb-8709-38b6edbb8e08.png)

Please take care of it. Thank you

**Comment by AlisherAmonulloev** [comment]
Unfortunately, it is not possible to run this repository as a website because it requires additional utilities that are not published.

I will inform the team about your request. However, it is unlikely that we will publish these utilities in the near future. In the meantime, you can use our online documentation: js.devexpress.com/Documentation.
